services:
  icoder:
    build: .
    container_name: icoder-backend-container
    ports:
      - "8080:8080"
    env_file:
      - env.properties
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
