spring.application.name=ICoder
server.port=${PORT}
spring.config.import=optional:file:env.properties
app.frontend.url=http://localhost:3000
# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
# Connection Pool
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JWT configuration
jwt.secret=${JWT_SECRET}
token.expiration=${TOKEN_EXPIRATION} 
refresh.token.expiration=${REFRESH_TOKEN_EXPIRATION} 
# Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${EMAIL}
spring.mail.password=${PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# External Services
alloowed.origins=${ALLOWED_ORIGIN}
judge0.api-url=${JUDGE0_URL}
judge0.auth-key=${JUDGE0_KEY}
judge0.host=${JUDGE0_HOST}
# Cloudinary
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}
profile.picture.folder=${PROFILE_PICTURE_FOLDER}
group.picture.folder=${GROUP_PICTURE_FOLDER}
# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
# Redis
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# Scrapers
cses.handle=${CSES_HANDLE}
cses.password=${CSES_PASSWORD}
cf.handle=${CODEFORCES_HANDLE}
cf.password=${CODEFORCES_PASSWORD}
atcoder.handle=${ATCODER_HANDLE}
atcoder.password=${ATCODER_PASSWORD}