spring.application.name=ICoder

server.port=${PORT}
spring.config.import=optional:file:env.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# control DB connections
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=${JWT_SECRET}
# 1 day
token.expiration=${TOKEN_EXPIRATION}
# 7 days
refresh.token.expiration=${REFRESH_TOKEN_EXPIRATION}

# Debugging (uncomment if needed)
# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.web=DEBUG

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL}
spring.mail.password=${PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application Email Settings
app.email.frontend-url=http://localhost:3000
app.email.sender-email=${EMAIL}
app.email.sender-name=ICoder
app.email.invitation-expiration-hours=24

alloowed.origins=${ALLOWED_ORIGIN}
judge0.api-url=${JUDGE0_URL}
judge0.auth-key=${JUDGE0_KEY}
judge0.host=${JUDGE0_HOST}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${CLOUD_API_KEY}
cloudinary.api-secret=${CLOUD_API_SECRET}

# Storage Configuration (using new configuration properties)
storage.profile-picture-folder=${PROFILE_PICTURE_FOLDER}
storage.group-picture-folder=${GROUP_PICTURE_FOLDER}
